# Generated by Django 3.1.2 on 2021-04-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='upload',
            new_name='url1',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail',
            new_name='url2',
        ),
    ]
