# Generated by Django 3.1.2 on 2021-04-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('ED', 'Education'), ('MU', 'Music'), ('NW', 'News'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
