# Generated by Django 3.1.2 on 2021-05-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0004_auto_20210430_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url2',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='url1',
            new_name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='unlikes',
            field=models.IntegerField(default=0),
        ),
    ]
