# Generated by Django 3.1.2 on 2021-05-07 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_auto_20210505_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='togglers',
            field=models.ManyToManyField(blank=True, related_name='toggled', to=settings.AUTH_USER_MODEL),
        ),
    ]
