# Generated by Django 3.1.2 on 2021-05-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0009_user_draugth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='draugth',
        ),
        migrations.AddField(
            model_name='user',
            name='draugth',
            field=models.ManyToManyField(blank=True, related_name='uploader', to='tube.Video'),
        ),
    ]
